### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Exagone313** [stsaz/cpspg#1]
Hello,

I have read some parts of your article on Habr and it is interesting.

Are you willing to add a license to your guide?

I would advise using a [Creative Commons](https://creativecommons.org/choose/) license (Attribution and/or ShareAlike and/or NonCommercial, depending to your choices) for the text, and a public domain license for the source code (maybe the [Unlicense](https://unlicense.org/)).

(It may be unnecessary to add a license for the source code, since the usage and description of APIs should not be copyrightable, though your source code goes further than that.)

Thank you for your work.

**Comment by stsaz** [comment]
Hello!

> I have read some parts of your article on Habr and it is interesting.

I'm glad to hear that!

> I would advise using a Creative Commons license

I absolutely agree with you.  Added CC-BY-SA.
